### ISSUE TITLE
Can't open the application While using UmAlQura date

### ISSUE THREAD

**Issue by AboShanab** [Klocman/Bulk-Crap-Uninstaller#177]
Hello, I have the latest version of BCUninstaller at Windows 10 x64, when open the application and the scan process is completed it crash and show me this window:
<img width="373" alt="screenshot_1" src="https://user-images.githubusercontent.com/12101368/36188135-2208e62a-115b-11e8-8f0f-8c2878738f71.png">
<img width="379" alt="screenshot_2" src="https://user-images.githubusercontent.com/12101368/36188136-222ecee4-115b-11e8-851b-5c09fc066c63.png">

Already sent the crash by the report feature but I just do an issue here to help you more if you want more details.

**Comment by Klocman** [comment]
Hello!

It looks like the crash report didn't get sent properly, Can you upload it here? Just start BCU, let it crash, and upload the new crash report that will appear in BCU's directory.

**Comment by AboShanab** [comment]
Sorry for the late @Klocman, https://transfer.sh/wnTD6/BCUninstaller.zip
Note: the crash file will be removed after 14 days automatically.

**Comment by Klocman** [comment]
Thank you, I think I fixed it. Can you download a test version [here](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1733915/Debug.zip) and check?

Note: You can upload files to Github just by dragging them over to the message box.

**Comment by AboShanab** [comment]
Still not working, here's the new screenshot of the crash:
<img width="376" alt="screenshot" src="https://user-images.githubusercontent.com/12101368/36344161-4bca86de-1427-11e8-9bb4-23743c72c21a.png">
and here's the crash report (also sent it using the crash report feature):
[BCUninstaller2.zip](https://github.com/Klocman/Bulk-Crap-Uninstaller/files/1733965/BCUninstaller2.zip)
at the end, Thank you about the tip, and your efforts.

**Comment by Klocman** [comment]
Good to hear, the fix will be released in a release this weekend.
